[package]
name = "bevy-man"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
bevy_xpbd_2d = "0.4.2"
lyon = "1.0.1"
rand = "0.8.5"
